version: "3.8"
services:
  ml-object-detection:
    build: .
    image: ml-object-detection
    restart: always
    container_name: ml-object-detection
    ports:
      - "8089:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MODEL_FILE=/model.onnx
      - MODEL_PROVIDER=YOLOV4
    volumes:
      - ./temp/yolov4/model.onnx:/model.onnx
